### ISSUE TITLE
Package header lacks version

### ISSUE THREAD

**Issue by wasamasa** [pitkali/pos-tip#8]
See title.  Why is there a constant holding the version, but no package header with a version?

Generally would proper version handling and package headers help with both MELPA and Marmalade, on both you'd have a proper About section, on Marmalade you'd have the correct version appearing as well.

If you wish, I can create a pull request for that, too.

**Comment by pitkali** [comment]
Because I happened to inherit the package in such a state after it being seemingly abandoned for extended period of time by its creator. The reason I seem to have ended in this position is me fixing some bug in a way how tooltip theming works that bugged me. I do not mind the responsibility though.

It did register with me that some changes need to be made with respect to package description, and other such administrative minutia (do we need a change log in the source file itself?), but I've been recently fairly busy with other things.

Suggestions/patches are welcome. Just keep in mind that I have a thing for proper documentation of changes, and things like that. My colleagues sometimes hate me for that, as they'd often prefer just to put an issue number instead of properly explaining what's going on in the commit message.  ;-)

**Comment by wasamasa** [comment]
Sounds good, I'll keep that in mind for my next pull request.

As for the Changelog, yes, I expected that to be in a separate file. But that would be something for a different issue.

**Comment by pitkali** [comment]
Change log is just an example of anachronism that needs to go, but I haven't got around to dealing with it.
